### ISSUE TITLE
[Feature Request] strip field values in result map

### ISSUE THREAD

**Issue by novabyte** [meh/cesso#5]
If I have a CSV file like:

```
test, test, test, test

```

When I use `Cesso` to read the file into a map the result looks like:

```
iex(1)> stream = Cesso.decode("test, test, test, test\n", columns: [:col1, :col2, :col3, :col4])
iex(2)> Enum.each(stream, &IO.inspect(&1)) 
%{col1: "test", col2: " test", col3: " test", col4: " test"}
:ok
```

The fields in the map have whitespace in them e.g. `col2: " test"`. Would you be interested in allowing `Cesso` to be configured to run the field values through `String.strip` to remove whitespace from the records?

**Comment by meh** [comment]
I think a more flexible way would be to allow a function as an option to transform the field, something like.

``` elixir
Cesso.decode("test, test, test, test\n", columns: [:col1, :col2, :col3, :col4], transform: &String.strip(&2))
```

What do you think?

**Comment by novabyte** [comment]
@meh That would work well for me :smile: 
Great project btw, and thanks for the fast reply!

**Comment by meh** [comment]
Uh, changed my mind, it would be more idiomatic to use `Stream.map` to work on the decoded CSV.

Since stripping is a common thing, I just added a boolean `:strip` option to the decoding.
