### ISSUE TITLE
Support for filtering out columns

### ISSUE THREAD

**Issue by mofirouz** [meh/cesso#6]
Hiya.

Firstly, awesome work! Thanks for this!

I was wondering if you could add another feature to this library : Support for retaining columns that I need. So effectively something like this:

```
Cesso.decode(stream, columns: [:firstname, :lastname, :email, :age, :gender], keep: [:firstname, :lastname], strip: true)
```

Cheers,
Mo.

**Comment by meh** [comment]
Now this is not that common and is easily done with `Stream.map`.

``` elixir
Cesso.decode(stream, columns: [:firstname, :lastname, :email, :age, :gender], strip: true)
  |> Stream.map &Dict.take(&1, [:firstname, :lastname])
```

**Comment by mofirouz** [comment]
Thanks for the solution :)
